# ONLY uncomment the following line in order to compile the nn-intermediate-activation.tex file!
# This will convert the PDF to a PNG file with transparent background which can subsequently be
# used in the PDF generated by compiling the main.tex file.

# END { system('convert -density 600 -background transparent -flatten output.pdf intermediate-activation.png'); }
